// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAslJRPQvLu8oWWSf3BVMzl7-R38c0zLR8',
    appId: '1:236045353421:web:18d0ced9a7c1cac1050484',
    messagingSenderId: '236045353421',
    projectId: 'noteapp-9de27',
    authDomain: 'noteapp-9de27.firebaseapp.com',
    storageBucket: 'noteapp-9de27.appspot.com',
    measurementId: 'G-ZE43LCXPCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kT_QP3xji14XG_XjhW12wlZhMEBb0KY',
    appId: '1:236045353421:android:2cf8ce5b6ebcef79050484',
    messagingSenderId: '236045353421',
    projectId: 'noteapp-9de27',
    storageBucket: 'noteapp-9de27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacRE9HuSoPsbl_3YrvMARYkHmBt840N0',
    appId: '1:236045353421:ios:dc4a8eaf6c6bc5dc050484',
    messagingSenderId: '236045353421',
    projectId: 'noteapp-9de27',
    storageBucket: 'noteapp-9de27.appspot.com',
    iosBundleId: 'com.example.noteFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacRE9HuSoPsbl_3YrvMARYkHmBt840N0',
    appId: '1:236045353421:ios:dc4a8eaf6c6bc5dc050484',
    messagingSenderId: '236045353421',
    projectId: 'noteapp-9de27',
    storageBucket: 'noteapp-9de27.appspot.com',
    iosBundleId: 'com.example.noteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAslJRPQvLu8oWWSf3BVMzl7-R38c0zLR8',
    appId: '1:236045353421:web:65c88502e0d7e4f2050484',
    messagingSenderId: '236045353421',
    projectId: 'noteapp-9de27',
    authDomain: 'noteapp-9de27.firebaseapp.com',
    storageBucket: 'noteapp-9de27.appspot.com',
    measurementId: 'G-E19XL5H286',
  );
}
